# Generated by Django 5.2.7 on 2025-11-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_badges_userstats_level1_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badges',
            name='icon',
            field=models.CharField(default='🥳', max_length=10),
        ),
        migrations.AddField(
            model_name='badges',
            name='key',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstats',
            name='last_completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userstats',
            name='longest_streak',
            field=models.IntegerField(default=0),
        ),
    ]
