# Generated by Django 6.0 on 2026-01-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_badges_icon_badges_key_userstats_last_completed_date_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameIndex(
                    model_name='xplog',
                    new_name='accounts_xp_user_id_aec3a3_idx',
                    old_name='accounts_xp_user_id_9a4e3c_idx',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'accounts_xp_user_id_9a4e3c_idx') THEN
                            ALTER INDEX accounts_xp_user_id_9a4e3c_idx RENAME TO accounts_xp_user_id_aec3a3_idx;
                        END IF;
                    END$$;
                    """,
                    reverse_sql="""
                    DO $$
                    BEGIN
                        IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'accounts_xp_user_id_aec3a3_idx') THEN
                            ALTER INDEX accounts_xp_user_id_aec3a3_idx RENAME TO accounts_xp_user_id_9a4e3c_idx;
                        END IF;
                    END$$;
                    """
                ),
            ],
        ),
        migrations.AddField(
            model_name='badges',
            name='condition',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userstats',
            name='challenges_completed_easy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='challenges_completed_hard',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='challenges_completed_medium',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='challenges_completed_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='habits_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='pomodoro_sessions_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
