# Generated by Django 5.2.12 on 2026-04-30 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_pushsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(choices=[('UTC', 'UTC'), ('Europe/London', 'London (GMT/BST)'), ('Europe/Paris', 'Paris (CET/CEST)'), ('Europe/Berlin', 'Berlin (CET/CEST)'), ('America/New_York', 'New York (EST/EDT)'), ('America/Chicago', 'Chicago (CST/CDT)'), ('America/Los_Angeles', 'Los Angeles (PST/PDT)'), ('Asia/Tokyo', 'Tokyo (JST)'), ('Asia/Shanghai', 'Shanghai (CST)'), ('Australia/Sydney', 'Sydney (AEDT/AEST)')], default='UTC', max_length=50)),
                ('is_enabled_habits', models.BooleanField(default=True)),
                ('notification_time_habits', models.TimeField(default='09:00')),
                ('is_enabled_challenges', models.BooleanField(default=True)),
                ('notification_time_challenges', models.TimeField(default='14:00')),
                ('is_enabled_pomodoro', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notification preferences',
            },
        ),
    ]
