import type { Metadata } from "next";
import { Geologica, Figtree } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./lib/auth/authContext";
import Navbar from "./components/Navbar";
import Topbar from "./components/Topbar";

const geologica = Geologica({
  variable: "--font-geologica",
  subsets: ["latin"],
});

const figtree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geologica.variable} ${figtree.variable} antialiased`}>
        <AuthProvider>
          <div className="h-screen flex flex-col">
            <Topbar />
            <div className="flex-grow">{children}</div>
            <Navbar />
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
