version: '3.8'

services:
  web:
    build: .
    container_name: django-backend
    ports:
      - "8000:8000"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./data:/app/data
    environment:
      - DJANGO_SECRET_KEY=django-insecure-mlc@tkg4$$lm_jes(4%^8$$1g7i=+-bhd14t_3uzngy5w$$y$$w#3s
      - DJANGO_DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1
    restart: unless-stopped
