[pytest]
addopts = --cov=accounts --cov-report=html --cov-report=term
testpaths = accounts/tests
python_files = test_*.py
[coverage:run]
branch = True
source = accounts
[coverage:report]
show_missing = True
skip_covered = True