# Generated by Django 5.2.12 on 2026-04-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
